// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/ironcore-dev/ironcore/client-go/informers/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Buckets returns a BucketInformer.
	Buckets() BucketInformer
	// BucketClasses returns a BucketClassInformer.
	BucketClasses() BucketClassInformer
	// BucketPools returns a BucketPoolInformer.
	BucketPools() BucketPoolInformer
	// Volumes returns a VolumeInformer.
	Volumes() VolumeInformer
	// VolumeClasses returns a VolumeClassInformer.
	VolumeClasses() VolumeClassInformer
	// VolumePools returns a VolumePoolInformer.
	VolumePools() VolumePoolInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Buckets returns a BucketInformer.
func (v *version) Buckets() BucketInformer {
	return &bucketInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// BucketClasses returns a BucketClassInformer.
func (v *version) BucketClasses() BucketClassInformer {
	return &bucketClassInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// BucketPools returns a BucketPoolInformer.
func (v *version) BucketPools() BucketPoolInformer {
	return &bucketPoolInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// Volumes returns a VolumeInformer.
func (v *version) Volumes() VolumeInformer {
	return &volumeInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VolumeClasses returns a VolumeClassInformer.
func (v *version) VolumeClasses() VolumeClassInformer {
	return &volumeClassInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// VolumePools returns a VolumePoolInformer.
func (v *version) VolumePools() VolumePoolInformer {
	return &volumePoolInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
