apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test

resources:
- ./manifests/ignition-secret.yaml
- ./manifests/networking.yaml
- ./manifests/volume.yaml
- ./manifests/machine.yaml

patches:
- path: patch-machineclassref.yaml
- path: patch-volume.yaml
