apiVersion: storage.ironcore.dev/v1alpha1
kind: Volume
metadata:
  name: volume-sample
spec:
  volumeClassRef:
    name: new-volumeclass-sample  # The new name of the volume class reference
  image: new-image:rootfs-abc
  volumePoolRef:
    name: new-volume-pool