apiVersion: storage.ironcore.dev/v1alpha1
kind: Volume
metadata:
  name: volume-sample
spec:
  volumeClassRef:
    name: volumeclass-sample
  image: gardenlinux:rootfs-image
  resources:
    storage: 10Gi
