apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases
- service.yaml

patches:
- path: patch-apiservice.yaml
  target:
    group: apiregistration.k8s.io
    kind: APIService
    version: v1

configurations:
- kustomizeconfig.yaml
