apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bases
  - service.yaml

patches:
  - path: patch-apiservice.yaml
    target:
      group: apiregistration.k8s.io
      version: v1
      kind: APIService

configurations:
  - kustomizeconfig.yaml
