---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      go-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "k8s.io/*"
      - dependency-name: "sigs.k8s.io/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      gh-actions-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      pip-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/docs"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      docker-dependencies:
        patterns:
          - "*"
