// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	types "k8s.io/apimachinery/pkg/types"
)

// LoadBalancerTargetRefApplyConfiguration represents a declarative configuration of the LoadBalancerTargetRef type for use
// with apply.
type LoadBalancerTargetRefApplyConfiguration struct {
	UID        *types.UID `json:"uid,omitempty"`
	Name       *string    `json:"name,omitempty"`
	ProviderID *string    `json:"providerID,omitempty"`
}

// LoadBalancerTargetRefApplyConfiguration constructs a declarative configuration of the LoadBalancerTargetRef type for use with
// apply.
func LoadBalancerTargetRef() *LoadBalancerTargetRefApplyConfiguration {
	return &LoadBalancerTargetRefApplyConfiguration{}
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *LoadBalancerTargetRefApplyConfiguration) WithUID(value types.UID) *LoadBalancerTargetRefApplyConfiguration {
	b.UID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LoadBalancerTargetRefApplyConfiguration) WithName(value string) *LoadBalancerTargetRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithProviderID sets the ProviderID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderID field is set to the value of the last call.
func (b *LoadBalancerTargetRefApplyConfiguration) WithProviderID(value string) *LoadBalancerTargetRefApplyConfiguration {
	b.ProviderID = &value
	return b
}
