version: "2"
run:
  concurrency: 4
linters:
  enable:
    - ginkgolinter
    - importas
    - misspell
    - revive
  settings:
    importas:
      alias:
        - pkg: github.com/ironcore-dev/ironcore/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: github.com/ironcore-dev/ironcore/internal/apis/(\w+)
          alias: $1
        - pkg: github.com/ironcore-dev/ironcore/internal/client/(\w+)
          alias: ${1}client
    misspell:
      ignore-rules:
        - strat
        - iritable
    revive:
      severity: error
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
        - name: if-return
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: 'exported: type name will be used as (.+) by other packages, and that stutters; consider calling this (.+)'
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: error
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
