site_name: OnMetal API
repo_url: https://github.com/onmetal/onmetal-api/
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  font:
    text: 'Work Sans'

plugins:
  - search

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true

nav:
  - Home: README.md
  - Concepts: README.md
  - Architecture: README.md
  - Usage: README.md
  - Development:
      - Local Development Setup: README.md
      - Documentation: development/documentation.md
      - Testing: README.md
      - Contribution Guide: development/contribution.md
  - API Reference:
      - Overview: api-reference/overview.md
      - Core: api-reference/core.md
      - Network: api-reference/network.md
      - Compute: api-reference/compute.md
      - Storage: api-reference/storage.md
      - Common: api-reference/common.md