site_name: Gardener on Metal / OnMetal API
repo_url: https://github.com/onmetal/onmetal-api/
edit_uri: edit/main/docs/
theme:
  icon:
    repo: fontawesome/brands/github
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.expand
  - navigation.indexes
  - navigation.top
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  font:
    text: 'Work Sans'

plugins:
- search

markdown_extensions:
- pymdownx.highlight
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.snippets
- codehilite
- admonition
- abbr
- toc:
    permalink: true

nav:
- Home: README.md
- Concepts:
    - Onmetal Runtime Interface: concepts/ori.md
    - Machine Exec: concepts/machine-exec-flow.md
- Architecture: README.md
- Usage: README.md
- Developer Guide:
  - Local Setup: development/setup.md
  - Documentation: development/documentation.md
  - Testing: development/testing.md
  - Contribution Guide: development/contribution.md
- Proposals: proposals/README.md
- API Reference:
  - Overview: api-reference/overview.md
  - IPAM: api-reference/ipam.md
  - Core: api-reference/core.md
  - Compute: api-reference/compute.md
  - Networking: api-reference/networking.md
  - Storage: api-reference/storage.md
  - Common: api-reference/common.md

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/onmetal/onmetal-api
