site_name: OnMetal API
repo_url: https://github.com/onmetal/onmetal-api/
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: 'Work Sans'

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - codehilite
  - admonition
  - abbr
  - toc:
      permalink: true

nav:
  - Home: README.md
  - Concepts: README.md
  - Architecture: README.md
  - Usage: README.md
  - Developer Guide:
      - Local Setup: development/setup.md
      - Documentation: development/documentation.md
      - Testing: development/testing.md
      - Contribution Guide: development/contribution.md
  - API Reference:
      - Overview: api-reference/overview.md
      - IPAM: api-reference/ipam.md
      - Compute: api-reference/compute.md
      - Storage: api-reference/storage.md
      - Common: api-reference/common.md