// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: event/v1alpha1/api.proto

package v1alpha1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	v1alpha1 "github.com/ironcore-dev/ironcore/iri/apis/meta/v1alpha1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *EventSpec             `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSpec() *EventSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type EventSpec struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	InvolvedObjectMeta *v1alpha1.ObjectMetadata `protobuf:"bytes,1,opt,name=involved_object_meta,json=involvedObjectMeta,proto3" json:"involved_object_meta,omitempty"`
	Reason             string                   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Type               string                   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	EventTime          int64                    `protobuf:"varint,5,opt,name=event_time,json=eventTime,proto3" json:"event_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EventSpec) Reset() {
	*x = EventSpec{}
	mi := &file_event_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSpec) ProtoMessage() {}

func (x *EventSpec) ProtoReflect() protoreflect.Message {
	mi := &file_event_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSpec.ProtoReflect.Descriptor instead.
func (*EventSpec) Descriptor() ([]byte, []int) {
	return file_event_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *EventSpec) GetInvolvedObjectMeta() *v1alpha1.ObjectMetadata {
	if x != nil {
		return x.InvolvedObjectMeta
	}
	return nil
}

func (x *EventSpec) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EventSpec) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventSpec) GetEventTime() int64 {
	if x != nil {
		return x.EventTime
	}
	return 0
}

var File_event_v1alpha1_api_proto protoreflect.FileDescriptor

const file_event_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"\x18event/v1alpha1/api.proto\x12\x0eevent.v1alpha1\x1a\x17meta/v1alpha1/api.proto\"6\n" +
	"\x05Event\x12-\n" +
	"\x04spec\x18\x02 \x01(\v2\x19.event.v1alpha1.EventSpecR\x04spec\"\xc1\x01\n" +
	"\tEventSpec\x12O\n" +
	"\x14involved_object_meta\x18\x01 \x01(\v2\x1d.meta.v1alpha1.ObjectMetadataR\x12involvedObjectMeta\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"event_time\x18\x05 \x01(\x03R\teventTimeB:Z8github.com/ironcore-dev/ironcore/iri/apis/event/v1alpha1b\x06proto3"

var (
	file_event_v1alpha1_api_proto_rawDescOnce sync.Once
	file_event_v1alpha1_api_proto_rawDescData []byte
)

func file_event_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_event_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_event_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_v1alpha1_api_proto_rawDesc), len(file_event_v1alpha1_api_proto_rawDesc)))
	})
	return file_event_v1alpha1_api_proto_rawDescData
}

var file_event_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_event_v1alpha1_api_proto_goTypes = []any{
	(*Event)(nil),                   // 0: event.v1alpha1.Event
	(*EventSpec)(nil),               // 1: event.v1alpha1.EventSpec
	(*v1alpha1.ObjectMetadata)(nil), // 2: meta.v1alpha1.ObjectMetadata
}
var file_event_v1alpha1_api_proto_depIdxs = []int32{
	1, // 0: event.v1alpha1.Event.spec:type_name -> event.v1alpha1.EventSpec
	2, // 1: event.v1alpha1.EventSpec.involved_object_meta:type_name -> meta.v1alpha1.ObjectMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_event_v1alpha1_api_proto_init() }
func file_event_v1alpha1_api_proto_init() {
	if File_event_v1alpha1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_v1alpha1_api_proto_rawDesc), len(file_event_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_event_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_event_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_event_v1alpha1_api_proto = out.File
	file_event_v1alpha1_api_proto_goTypes = nil
	file_event_v1alpha1_api_proto_depIdxs = nil
}
