apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: onmetal-system
  name: onmetal-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
