apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ironcore-system
  name: ironcore-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
