// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// LoadBalancerListerExpansion allows custom methods to be added to
// LoadBalancerLister.
type LoadBalancerListerExpansion interface{}

// LoadBalancerNamespaceListerExpansion allows custom methods to be added to
// LoadBalancerNamespaceLister.
type LoadBalancerNamespaceListerExpansion interface{}

// LoadBalancerRoutingListerExpansion allows custom methods to be added to
// LoadBalancerRoutingLister.
type LoadBalancerRoutingListerExpansion interface{}

// LoadBalancerRoutingNamespaceListerExpansion allows custom methods to be added to
// LoadBalancerRoutingNamespaceLister.
type LoadBalancerRoutingNamespaceListerExpansion interface{}

// NATGatewayListerExpansion allows custom methods to be added to
// NATGatewayLister.
type NATGatewayListerExpansion interface{}

// NATGatewayNamespaceListerExpansion allows custom methods to be added to
// NATGatewayNamespaceLister.
type NATGatewayNamespaceListerExpansion interface{}

// NetworkListerExpansion allows custom methods to be added to
// NetworkLister.
type NetworkListerExpansion interface{}

// NetworkNamespaceListerExpansion allows custom methods to be added to
// NetworkNamespaceLister.
type NetworkNamespaceListerExpansion interface{}

// NetworkInterfaceListerExpansion allows custom methods to be added to
// NetworkInterfaceLister.
type NetworkInterfaceListerExpansion interface{}

// NetworkInterfaceNamespaceListerExpansion allows custom methods to be added to
// NetworkInterfaceNamespaceLister.
type NetworkInterfaceNamespaceListerExpansion interface{}

// NetworkPolicyListerExpansion allows custom methods to be added to
// NetworkPolicyLister.
type NetworkPolicyListerExpansion interface{}

// NetworkPolicyNamespaceListerExpansion allows custom methods to be added to
// NetworkPolicyNamespaceLister.
type NetworkPolicyNamespaceListerExpansion interface{}

// VirtualIPListerExpansion allows custom methods to be added to
// VirtualIPLister.
type VirtualIPListerExpansion interface{}

// VirtualIPNamespaceListerExpansion allows custom methods to be added to
// VirtualIPNamespaceLister.
type VirtualIPNamespaceListerExpansion interface{}
