//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in DaemonEndpoint) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.DaemonEndpoint"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EFIVar) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.EFIVar"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EmptyDiskVolumeSource) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.EmptyDiskVolumeSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EphemeralNetworkInterfaceSource) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.EphemeralNetworkInterfaceSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in EphemeralVolumeSource) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.EphemeralVolumeSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in LocalDiskVolumeSource) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.LocalDiskVolumeSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Machine) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.Machine"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachineClass) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachineClass"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachineClassList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachineClassList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachineCondition) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachineCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachineExecOptions) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachineExecOptions"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachineGuestConfig) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachineGuestConfig"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachineList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachineList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachinePool) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachinePool"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachinePoolAddress) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachinePoolAddress"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachinePoolCondition) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachinePoolCondition"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachinePoolDaemonEndpoints) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachinePoolDaemonEndpoints"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachinePoolList) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachinePoolList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachinePoolSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachinePoolSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachinePoolStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachinePoolStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachineSpec) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachineSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in MachineStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.MachineStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterface) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.NetworkInterface"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceSource) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.NetworkInterfaceSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in NetworkInterfaceStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.NetworkInterfaceStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Volume) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.Volume"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeSource) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.VolumeSource"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VolumeStatus) OpenAPIModelName() string {
	return "com.github.ironcore-dev.ironcore.api.compute.v1alpha1.VolumeStatus"
}
