// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	storagev1alpha1 "github.com/ironcore-dev/ironcore/api/storage/v1alpha1"
	applyconfigurationsstoragev1alpha1 "github.com/ironcore-dev/ironcore/client-go/applyconfigurations/storage/v1alpha1"
	scheme "github.com/ironcore-dev/ironcore/client-go/ironcore/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VolumeSnapshotContentsGetter has a method to return a VolumeSnapshotContentInterface.
// A group's client should implement this interface.
type VolumeSnapshotContentsGetter interface {
	VolumeSnapshotContents(namespace string) VolumeSnapshotContentInterface
}

// VolumeSnapshotContentInterface has methods to work with VolumeSnapshotContent resources.
type VolumeSnapshotContentInterface interface {
	Create(ctx context.Context, volumeSnapshotContent *storagev1alpha1.VolumeSnapshotContent, opts v1.CreateOptions) (*storagev1alpha1.VolumeSnapshotContent, error)
	Update(ctx context.Context, volumeSnapshotContent *storagev1alpha1.VolumeSnapshotContent, opts v1.UpdateOptions) (*storagev1alpha1.VolumeSnapshotContent, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*storagev1alpha1.VolumeSnapshotContent, error)
	List(ctx context.Context, opts v1.ListOptions) (*storagev1alpha1.VolumeSnapshotContentList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *storagev1alpha1.VolumeSnapshotContent, err error)
	Apply(ctx context.Context, volumeSnapshotContent *applyconfigurationsstoragev1alpha1.VolumeSnapshotContentApplyConfiguration, opts v1.ApplyOptions) (result *storagev1alpha1.VolumeSnapshotContent, err error)
	VolumeSnapshotContentExpansion
}

// volumeSnapshotContents implements VolumeSnapshotContentInterface
type volumeSnapshotContents struct {
	*gentype.ClientWithListAndApply[*storagev1alpha1.VolumeSnapshotContent, *storagev1alpha1.VolumeSnapshotContentList, *applyconfigurationsstoragev1alpha1.VolumeSnapshotContentApplyConfiguration]
}

// newVolumeSnapshotContents returns a VolumeSnapshotContents
func newVolumeSnapshotContents(c *StorageV1alpha1Client, namespace string) *volumeSnapshotContents {
	return &volumeSnapshotContents{
		gentype.NewClientWithListAndApply[*storagev1alpha1.VolumeSnapshotContent, *storagev1alpha1.VolumeSnapshotContentList, *applyconfigurationsstoragev1alpha1.VolumeSnapshotContentApplyConfiguration](
			"volumesnapshotcontents",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *storagev1alpha1.VolumeSnapshotContent { return &storagev1alpha1.VolumeSnapshotContent{} },
			func() *storagev1alpha1.VolumeSnapshotContentList { return &storagev1alpha1.VolumeSnapshotContentList{} },
		),
	}
}
