---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.api.onmetal.de
  resources:
  - machineclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.api.onmetal.de
  resources:
  - machinepools
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.api.onmetal.de
  resources:
  - machinepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.api.onmetal.de
  resources:
  - machines
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.api.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - compute.api.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - networkinterfaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.api.onmetal.de
  resources:
  - virtualips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.api.onmetal.de
  resources:
  - volumes
  verbs:
  - get
  - list
  - watch
