// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore/api/storage/v1alpha1"
	storagev1alpha1 "github.com/ironcore-dev/ironcore/client-go/applyconfigurations/storage/v1alpha1"
	typedstoragev1alpha1 "github.com/ironcore-dev/ironcore/client-go/ironcore/versioned/typed/storage/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVolumePools implements VolumePoolInterface
type fakeVolumePools struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.VolumePool, *v1alpha1.VolumePoolList, *storagev1alpha1.VolumePoolApplyConfiguration]
	Fake *FakeStorageV1alpha1
}

func newFakeVolumePools(fake *FakeStorageV1alpha1) typedstoragev1alpha1.VolumePoolInterface {
	return &fakeVolumePools{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.VolumePool, *v1alpha1.VolumePoolList, *storagev1alpha1.VolumePoolApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("volumepools"),
			v1alpha1.SchemeGroupVersion.WithKind("VolumePool"),
			func() *v1alpha1.VolumePool { return &v1alpha1.VolumePool{} },
			func() *v1alpha1.VolumePoolList { return &v1alpha1.VolumePoolList{} },
			func(dst, src *v1alpha1.VolumePoolList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VolumePoolList) []*v1alpha1.VolumePool { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.VolumePoolList, items []*v1alpha1.VolumePool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
