# permissions for end users to view clusterprefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterprefix-viewer-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixes/status
  verbs:
  - get
