# permissions for end users to edit clusterprefixallocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterprefixallocation-editor-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixallocations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixallocations/status
  verbs:
  - get
