# permissions for end users to view clusterprefixallocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterprefixallocation-viewer-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixallocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - clusterprefixallocations/status
  verbs:
  - get
