# permissions for end users to view clusterprefixallocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterprefixallocation-viewer-role
rules:
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - clusterprefixallocations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - clusterprefixallocations/status
    verbs:
      - get
