# permissions for end users to view clusterprefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterprefix-viewer-role
rules:
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - clusterprefixes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - clusterprefixes/status
    verbs:
      - get
