# permissions for end users to edit ipamranges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipamrange-editor-role
rules:
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - ipamranges
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - ipamranges/status
    verbs:
      - get
