# permissions for end users to view ipamranges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipamrange-viewer-role
rules:
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - ipamranges
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - ipamranges/status
    verbs:
      - get
