# permissions for end users to view prefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefix-viewer-role
rules:
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - prefixes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - prefixes/status
    verbs:
      - get
