# permissions for end users to edit prefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefix-editor-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - prefixes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - prefixes/status
  verbs:
  - get
