# permissions for end users to view prefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefix-viewer-role
rules:
- apiGroups:
  - network.onmetal.de
  resources:
  - prefixes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.onmetal.de
  resources:
  - prefixes/status
  verbs:
  - get
