---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests/bucketpoolclient
  verbs:
  - create
- apiGroups:
  - storage.ironcore.dev
  resources:
  - bucketclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.ironcore.dev
  resources:
  - bucketpools
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.ironcore.dev
  resources:
  - bucketpools/status
  - buckets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.ironcore.dev
  resources:
  - buckets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.ironcore.dev
  resources:
  - buckets/finalizers
  verbs:
  - update
