// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/ironcore-dev/ironcore/api/storage/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BucketPoolLister helps list BucketPools.
// All objects returned here must be treated as read-only.
type BucketPoolLister interface {
	// List lists all BucketPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.BucketPool, err error)
	// Get retrieves the BucketPool from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.BucketPool, error)
	BucketPoolListerExpansion
}

// bucketPoolLister implements the BucketPoolLister interface.
type bucketPoolLister struct {
	indexer cache.Indexer
}

// NewBucketPoolLister returns a new BucketPoolLister.
func NewBucketPoolLister(indexer cache.Indexer) BucketPoolLister {
	return &bucketPoolLister{indexer: indexer}
}

// List lists all BucketPools in the indexer.
func (s *bucketPoolLister) List(selector labels.Selector) (ret []*v1alpha1.BucketPool, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BucketPool))
	})
	return ret, err
}

// Get retrieves the BucketPool from the index for a given name.
func (s *bucketPoolLister) Get(name string) (*v1alpha1.BucketPool, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("bucketpool"), name)
	}
	return obj.(*v1alpha1.BucketPool), nil
}
