// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	storagev1alpha1 "github.com/ironcore-dev/ironcore/api/storage/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VolumePoolLister helps list VolumePools.
// All objects returned here must be treated as read-only.
type VolumePoolLister interface {
	// List lists all VolumePools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1alpha1.VolumePool, err error)
	// Get retrieves the VolumePool from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*storagev1alpha1.VolumePool, error)
	VolumePoolListerExpansion
}

// volumePoolLister implements the VolumePoolLister interface.
type volumePoolLister struct {
	listers.ResourceIndexer[*storagev1alpha1.VolumePool]
}

// NewVolumePoolLister returns a new VolumePoolLister.
func NewVolumePoolLister(indexer cache.Indexer) VolumePoolLister {
	return &volumePoolLister{listers.New[*storagev1alpha1.VolumePool](indexer, storagev1alpha1.Resource("volumepool"))}
}
