// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	storagev1alpha1 "github.com/ironcore-dev/ironcore/api/storage/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VolumeSnapshotContentLister helps list VolumeSnapshotContents.
// All objects returned here must be treated as read-only.
type VolumeSnapshotContentLister interface {
	// List lists all VolumeSnapshotContents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1alpha1.VolumeSnapshotContent, err error)
	// VolumeSnapshotContents returns an object that can list and get VolumeSnapshotContents.
	VolumeSnapshotContents(namespace string) VolumeSnapshotContentNamespaceLister
	VolumeSnapshotContentListerExpansion
}

// volumeSnapshotContentLister implements the VolumeSnapshotContentLister interface.
type volumeSnapshotContentLister struct {
	listers.ResourceIndexer[*storagev1alpha1.VolumeSnapshotContent]
}

// NewVolumeSnapshotContentLister returns a new VolumeSnapshotContentLister.
func NewVolumeSnapshotContentLister(indexer cache.Indexer) VolumeSnapshotContentLister {
	return &volumeSnapshotContentLister{listers.New[*storagev1alpha1.VolumeSnapshotContent](indexer, storagev1alpha1.Resource("volumesnapshotcontent"))}
}

// VolumeSnapshotContents returns an object that can list and get VolumeSnapshotContents.
func (s *volumeSnapshotContentLister) VolumeSnapshotContents(namespace string) VolumeSnapshotContentNamespaceLister {
	return volumeSnapshotContentNamespaceLister{listers.NewNamespaced[*storagev1alpha1.VolumeSnapshotContent](s.ResourceIndexer, namespace)}
}

// VolumeSnapshotContentNamespaceLister helps list and get VolumeSnapshotContents.
// All objects returned here must be treated as read-only.
type VolumeSnapshotContentNamespaceLister interface {
	// List lists all VolumeSnapshotContents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*storagev1alpha1.VolumeSnapshotContent, err error)
	// Get retrieves the VolumeSnapshotContent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*storagev1alpha1.VolumeSnapshotContent, error)
	VolumeSnapshotContentNamespaceListerExpansion
}

// volumeSnapshotContentNamespaceLister implements the VolumeSnapshotContentNamespaceLister
// interface.
type volumeSnapshotContentNamespaceLister struct {
	listers.ResourceIndexer[*storagev1alpha1.VolumeSnapshotContent]
}
