// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	storagev1alpha1 "github.com/ironcore-dev/ironcore/api/storage/v1alpha1"
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BucketPoolConditionApplyConfiguration represents a declarative configuration of the BucketPoolCondition type for use
// with apply.
//
// BucketPoolCondition is one of the conditions of a BucketPool.
type BucketPoolConditionApplyConfiguration struct {
	// Type is the type of the condition.
	Type *storagev1alpha1.BucketPoolConditionType `json:"type,omitempty"`
	// Status is the status of the condition.
	Status *v1.ConditionStatus `json:"status,omitempty"`
	// Reason is a machine-readable indication of why the condition is in a certain state.
	Reason *string `json:"reason,omitempty"`
	// Message is a human-readable explanation of why the condition has a certain reason / state.
	Message *string `json:"message,omitempty"`
	// ObservedGeneration represents the .metadata.generation that the condition was set based upon.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// LastUpdateTime is the last time this condition was updated.
	LastUpdateTime *metav1.Time `json:"lastUpdateTime,omitempty"`
	// LastTransitionTime is the last time the status of a condition has transitioned from one state to another.
	LastTransitionTime *metav1.Time `json:"lastTransitionTime,omitempty"`
}

// BucketPoolConditionApplyConfiguration constructs a declarative configuration of the BucketPoolCondition type for use with
// apply.
func BucketPoolCondition() *BucketPoolConditionApplyConfiguration {
	return &BucketPoolConditionApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *BucketPoolConditionApplyConfiguration) WithType(value storagev1alpha1.BucketPoolConditionType) *BucketPoolConditionApplyConfiguration {
	b.Type = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *BucketPoolConditionApplyConfiguration) WithStatus(value v1.ConditionStatus) *BucketPoolConditionApplyConfiguration {
	b.Status = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *BucketPoolConditionApplyConfiguration) WithReason(value string) *BucketPoolConditionApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *BucketPoolConditionApplyConfiguration) WithMessage(value string) *BucketPoolConditionApplyConfiguration {
	b.Message = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *BucketPoolConditionApplyConfiguration) WithObservedGeneration(value int64) *BucketPoolConditionApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithLastUpdateTime sets the LastUpdateTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdateTime field is set to the value of the last call.
func (b *BucketPoolConditionApplyConfiguration) WithLastUpdateTime(value metav1.Time) *BucketPoolConditionApplyConfiguration {
	b.LastUpdateTime = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *BucketPoolConditionApplyConfiguration) WithLastTransitionTime(value metav1.Time) *BucketPoolConditionApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}
