// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	commonv1alpha1 "github.com/ironcore-dev/ironcore/api/common/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// BucketSpecApplyConfiguration represents a declarative configuration of the BucketSpec type for use
// with apply.
//
// BucketSpec defines the desired state of Bucket
type BucketSpecApplyConfiguration struct {
	// BucketClassRef is the BucketClass of a bucket
	// If empty, an external controller has to provision the bucket.
	BucketClassRef *v1.LocalObjectReference `json:"bucketClassRef,omitempty"`
	// BucketPoolSelector selects a suitable BucketPoolRef by the given labels.
	BucketPoolSelector map[string]string `json:"bucketPoolSelector,omitempty"`
	// BucketPoolRef indicates which BucketPool to use for a bucket.
	// If unset, the scheduler will figure out a suitable BucketPoolRef.
	BucketPoolRef *v1.LocalObjectReference `json:"bucketPoolRef,omitempty"`
	// Tolerations define tolerations the Bucket has. Only any BucketPool whose taints
	// covered by Tolerations will be considered to host the Bucket.
	Tolerations []commonv1alpha1.Toleration `json:"tolerations,omitempty"`
}

// BucketSpecApplyConfiguration constructs a declarative configuration of the BucketSpec type for use with
// apply.
func BucketSpec() *BucketSpecApplyConfiguration {
	return &BucketSpecApplyConfiguration{}
}

// WithBucketClassRef sets the BucketClassRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BucketClassRef field is set to the value of the last call.
func (b *BucketSpecApplyConfiguration) WithBucketClassRef(value v1.LocalObjectReference) *BucketSpecApplyConfiguration {
	b.BucketClassRef = &value
	return b
}

// WithBucketPoolSelector puts the entries into the BucketPoolSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the BucketPoolSelector field,
// overwriting an existing map entries in BucketPoolSelector field with the same key.
func (b *BucketSpecApplyConfiguration) WithBucketPoolSelector(entries map[string]string) *BucketSpecApplyConfiguration {
	if b.BucketPoolSelector == nil && len(entries) > 0 {
		b.BucketPoolSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.BucketPoolSelector[k] = v
	}
	return b
}

// WithBucketPoolRef sets the BucketPoolRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BucketPoolRef field is set to the value of the last call.
func (b *BucketSpecApplyConfiguration) WithBucketPoolRef(value v1.LocalObjectReference) *BucketSpecApplyConfiguration {
	b.BucketPoolRef = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *BucketSpecApplyConfiguration) WithTolerations(values ...commonv1alpha1.Toleration) *BucketSpecApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}
