// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// VolumeEncryptionApplyConfiguration represents a declarative configuration of the VolumeEncryption type for use
// with apply.
type VolumeEncryptionApplyConfiguration struct {
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
}

// VolumeEncryptionApplyConfiguration constructs a declarative configuration of the VolumeEncryption type for use with
// apply.
func VolumeEncryption() *VolumeEncryptionApplyConfiguration {
	return &VolumeEncryptionApplyConfiguration{}
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *VolumeEncryptionApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *VolumeEncryptionApplyConfiguration {
	b.SecretRef = &value
	return b
}
