// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// VolumeDataSourceApplyConfiguration represents a declarative configuration of the VolumeDataSource type for use
// with apply.
type VolumeDataSourceApplyConfiguration struct {
	VolumeSnapshotRef *v1.LocalObjectReference `json:"volumeSnapshotRef,omitempty"`
	OSImage           *string                  `json:"osImage,omitempty"`
}

// VolumeDataSourceApplyConfiguration constructs a declarative configuration of the VolumeDataSource type for use with
// apply.
func VolumeDataSource() *VolumeDataSourceApplyConfiguration {
	return &VolumeDataSourceApplyConfiguration{}
}

// WithVolumeSnapshotRef sets the VolumeSnapshotRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeSnapshotRef field is set to the value of the last call.
func (b *VolumeDataSourceApplyConfiguration) WithVolumeSnapshotRef(value v1.LocalObjectReference) *VolumeDataSourceApplyConfiguration {
	b.VolumeSnapshotRef = &value
	return b
}

// WithOSImage sets the OSImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OSImage field is set to the value of the last call.
func (b *VolumeDataSourceApplyConfiguration) WithOSImage(value string) *VolumeDataSourceApplyConfiguration {
	b.OSImage = &value
	return b
}
