/*
 * Copyright (c) 2022 by the IronCore authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/ironcore-dev/ironcore/api/ipam/v1alpha1"
	ipamv1alpha1 "github.com/ironcore-dev/ironcore/client-go/applyconfigurations/ipam/v1alpha1"
	scheme "github.com/ironcore-dev/ironcore/client-go/ironcore/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PrefixesGetter has a method to return a PrefixInterface.
// A group's client should implement this interface.
type PrefixesGetter interface {
	Prefixes(namespace string) PrefixInterface
}

// PrefixInterface has methods to work with Prefix resources.
type PrefixInterface interface {
	Create(ctx context.Context, prefix *v1alpha1.Prefix, opts v1.CreateOptions) (*v1alpha1.Prefix, error)
	Update(ctx context.Context, prefix *v1alpha1.Prefix, opts v1.UpdateOptions) (*v1alpha1.Prefix, error)
	UpdateStatus(ctx context.Context, prefix *v1alpha1.Prefix, opts v1.UpdateOptions) (*v1alpha1.Prefix, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Prefix, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PrefixList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Prefix, err error)
	Apply(ctx context.Context, prefix *ipamv1alpha1.PrefixApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Prefix, err error)
	ApplyStatus(ctx context.Context, prefix *ipamv1alpha1.PrefixApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Prefix, err error)
	PrefixExpansion
}

// prefixes implements PrefixInterface
type prefixes struct {
	client rest.Interface
	ns     string
}

// newPrefixes returns a Prefixes
func newPrefixes(c *IpamV1alpha1Client, namespace string) *prefixes {
	return &prefixes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the prefix, and returns the corresponding prefix object, and an error if there is any.
func (c *prefixes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Prefix, err error) {
	result = &v1alpha1.Prefix{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prefixes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Prefixes that match those selectors.
func (c *prefixes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PrefixList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PrefixList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("prefixes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested prefixes.
func (c *prefixes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("prefixes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a prefix and creates it.  Returns the server's representation of the prefix, and an error, if there is any.
func (c *prefixes) Create(ctx context.Context, prefix *v1alpha1.Prefix, opts v1.CreateOptions) (result *v1alpha1.Prefix, err error) {
	result = &v1alpha1.Prefix{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("prefixes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(prefix).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a prefix and updates it. Returns the server's representation of the prefix, and an error, if there is any.
func (c *prefixes) Update(ctx context.Context, prefix *v1alpha1.Prefix, opts v1.UpdateOptions) (result *v1alpha1.Prefix, err error) {
	result = &v1alpha1.Prefix{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prefixes").
		Name(prefix.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(prefix).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *prefixes) UpdateStatus(ctx context.Context, prefix *v1alpha1.Prefix, opts v1.UpdateOptions) (result *v1alpha1.Prefix, err error) {
	result = &v1alpha1.Prefix{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("prefixes").
		Name(prefix.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(prefix).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the prefix and deletes it. Returns an error if one occurs.
func (c *prefixes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prefixes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *prefixes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("prefixes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched prefix.
func (c *prefixes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Prefix, err error) {
	result = &v1alpha1.Prefix{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("prefixes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied prefix.
func (c *prefixes) Apply(ctx context.Context, prefix *ipamv1alpha1.PrefixApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Prefix, err error) {
	if prefix == nil {
		return nil, fmt.Errorf("prefix provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(prefix)
	if err != nil {
		return nil, err
	}
	name := prefix.Name
	if name == nil {
		return nil, fmt.Errorf("prefix.Name must be provided to Apply")
	}
	result = &v1alpha1.Prefix{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("prefixes").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *prefixes) ApplyStatus(ctx context.Context, prefix *ipamv1alpha1.PrefixApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Prefix, err error) {
	if prefix == nil {
		return nil, fmt.Errorf("prefix provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(prefix)
	if err != nil {
		return nil, err
	}

	name := prefix.Name
	if name == nil {
		return nil, fmt.Errorf("prefix.Name must be provided to Apply")
	}

	result = &v1alpha1.Prefix{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("prefixes").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
