// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore/api/compute/v1alpha1"
	computev1alpha1 "github.com/ironcore-dev/ironcore/client-go/applyconfigurations/compute/v1alpha1"
	typedcomputev1alpha1 "github.com/ironcore-dev/ironcore/client-go/ironcore/versioned/typed/compute/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeMachines implements MachineInterface
type fakeMachines struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.Machine, *v1alpha1.MachineList, *computev1alpha1.MachineApplyConfiguration]
	Fake *FakeComputeV1alpha1
}

func newFakeMachines(fake *FakeComputeV1alpha1, namespace string) typedcomputev1alpha1.MachineInterface {
	return &fakeMachines{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.Machine, *v1alpha1.MachineList, *computev1alpha1.MachineApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("machines"),
			v1alpha1.SchemeGroupVersion.WithKind("Machine"),
			func() *v1alpha1.Machine { return &v1alpha1.Machine{} },
			func() *v1alpha1.MachineList { return &v1alpha1.MachineList{} },
			func(dst, src *v1alpha1.MachineList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.MachineList) []*v1alpha1.Machine { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.MachineList, items []*v1alpha1.Machine) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
