apiVersion: compute.api.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: machine-sample
spec:
  machineClassRef:
    name: machineclass-sample
  #  machinePoolRef:
  #    name: default
  image: my-image
  volumes:
    - name: rootdisk # first disk is root disk
      # priority: 0 # optional
      volumeRef:
        name: my-volume
  ignitionRef:
    name: my-ignition-configmap
