apiVersion: compute.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: machine-sample
spec:
  hostname: machine-sample
  machineClass:
    name: x3.xlarge
  machinePool:
    name: default
  image: myimage_repo_location
  volumeAttachments:
    - name: rootdisk # first disk is root disk
      # priority: 0 # optional
      volumeClaim:
        ref:
          name: my-volumeclaim
  ignition:
    name: my-ignition-configmap
