apiVersion: compute.api.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: machine-sample
spec:
  machineClass:
    name: x3.xlarge
  machinePool:
    name: default
  image: myimage_repo_location
  volumes:
    - name: rootdisk # first disk is root disk
      # priority: 0 # optional
      volumeClaimRef:
        name: my-volumeclaim
  ignition:
    name: my-ignition-configmap
