apiVersion: compute.api.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: machine-sample
spec:
  machineClassRef:
    name: machineclass-sample
  machinePoolRef:
    name: default
  image: myimage_repo_location
  volumes:
    - name: rootdisk # first disk is root disk
      # priority: 0 # optional
      volumeClaimRef:
        name: my-volumeclaim
  ignitionRef:
    name: my-ignition-configmap
