apiVersion: network.onmetal.de/v1alpha1
kind: ClusterPrefix
metadata:
  name: clusterprefix-sample
  labels:
    subnet-type: public
spec:
  prefix: 10.0.0.0/8
---
apiVersion: network.onmetal.de/v1alpha1
kind: ClusterPrefix
metadata:
  name: clusterprefix-child-sample
spec:
  prefixLength: 24
  parentRef:
    name: clusterprefix-sample
---
apiVersion: network.onmetal.de/v1alpha1
kind: ClusterPrefix
metadata:
  name: clusterprefix-child-sample-selector
  labels:
    subnet-type: public
    subnet-sub: ok
spec:
  prefixLength: 24
  parentSelector:
    matchLabels:
      subnet-type: public
---
apiVersion: network.onmetal.de/v1alpha1
kind: Prefix
metadata:
  name: clusterprefix-child-sample-selector
spec:
  prefixLength: 24
  parentSelector:
    kind: ClusterPrefix
    matchLabels:
      subnet-type: public
---
apiVersion: network.onmetal.de/v1alpha1
kind: IP
metadata:
  name: clusterprefix-child-sample-selector
spec:
  prefixSelector:
    kind: ClusterPrefix
    matchLabels:
      subnet-type: public
      subnet-sub: ok
