apiVersion: networking.api.onmetal.de/v1alpha1
kind: LoadBalancer
metadata:
  namespace: default
  name: loadbalancer-sample
spec:
  type: Public
  ipFamilies: [IPv4]
  networkRef:
    name: network-sample
  networkInterfaceSelector:
    matchLabels:
      app: web
  ports:
  - port: 80
#status:
#  ips:
#  - 10.0.0.1 # The publicly available ip of the load balancer
