apiVersion: networking.api.onmetal.de/v1alpha1
kind: NATGateway
metadata:
  namespace: default
  name: natgateway-sample
spec:
  type: Public
  ipFamilies: [ IPv4 ]
  ips:
    - name: ip1
  portsPerNetworkInterface: 64
  networkRef:
    name: network-sample
  networkInterfaceSelector:
    matchLabels:
      app: web
#status:
#  ips:
#  - name: ip1
#    ip: 10.0.0.1
