apiVersion: ipam.api.onmetal.de/v1alpha1
kind: Subnet
metadata:
  name: subnet-sample
spec:
  #  parentSubnet:
  #    name: mySubnet1
  routingDomain:
    name: routingdomain-sample
  ranges:
    - cidr: 10.0.0.0/16
  # size: "/12" # derived from the parent subnet
#status:
#  state: Up