apiVersion: storage.ironcore.dev/v1alpha1
kind: BucketPool
metadata:
  name: bucketpool-sample
spec:
  providerID: ironcore://shared
#status:
#  state: Available
#  available:
#    ironcore.dev/fast-class: 10Gi
#    ironcore.dev/slow-class: 100Gi
