apiVersion: storage.ironcore.dev/v1alpha1
kind: VolumePool
metadata:
  name: volumepool-sample
spec:
  providerID: ironcore://shared
#status:
#  state: Available
#  available:
#    ironcore.dev/fast-class: 10Gi
#    ironcore.dev/slow-class: 100Gi
