apiVersion: network.onmetal.de/v1alpha1
kind: RoutingDomain
metadata:
  name: routingdomain-sample
---
apiVersion: network.onmetal.de/v1alpha1
kind: Subnet
metadata:
  name: subnet-sample
spec:
  routingDomain:
    name: routingdomain-sample
  ranges:
    - cidr: 192.168.0.0/24
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ignition-sample
data:
  ignition.yaml: |
    my: ignition
---
apiVersion: compute.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: machine-sample
spec:
  hostname: myhost
  machineClass:
    name: x3.xlarge
  machinePool:
    name: default
  image: myimage_repo_location
  sshPublicKeys:
    - name: mykey
  interfaces:
    - name: myinterface
      priority: 0 # optional
      target:
        name: subnet-sample
    - name: myotherinterface
      target:
        name: subnet-sample
  securityGroups:
    - name: mysecgroup1
  ignition:
    name: ignition-sample
  efiVars:
    - name: PK
      uuid: 8be4df61-93ca-11d2-aa0d-00e098032b8c
      value: pki.Gardenlinux.io/kernel.crt
---
apiVersion: compute.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: machine-sample-2
spec:
  hostname: myhost-2
  machineClass:
    name: x3.xlarge
  machinePool:
    name: default
  image: myimage_repo_location
  sshPublicKeys:
    - name: mykey
  interfaces:
    - name: myinterface
      priority: 0 # optional
      target:
        name: subnet-sample
  securityGroups:
    - name: mysecgroup1
  ignition:
    name: ignition-sample
  efiVars:
    - name: PK
      uuid: 8be4df61-93ca-11d2-aa0d-00e098032b8c
      value: pki.Gardenlinux.io/kernel.crt
