# permissions for end users to edit ips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ip-editor-role
rules:
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - ips
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ipam.api.onmetal.de
    resources:
      - ips/status
    verbs:
      - get
