# permissions for end users to edit machinepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinepool-editor-role
rules:
  - apiGroups:
      - compute.ironcore.dev
    resources:
      - machinepools
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - compute.ironcore.dev
    resources:
      - machinepools/status
    verbs:
      - get
