# permissions for end users to edit machineclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machineclass-editor-role
rules:
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.onmetal.de
  resources:
  - machineclasses/status
  verbs:
  - get
