# permissions for end users to view machineclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machineclass-viewer-role
rules:
  - apiGroups:
      - compute.api.onmetal.de
    resources:
      - machineclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - compute.api.onmetal.de
    resources:
      - machineclasses/status
    verbs:
      - get
