# permissions for end users to view machinepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinepool-viewer-role
rules:
  - apiGroups:
      - compute.ironcore.dev
    resources:
      - machinepools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - compute.ironcore.dev
    resources:
      - machinepools/status
    verbs:
      - get
