# permissions for end users to edit prefixallocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefixallocation-editor-role
rules:
  - apiGroups:
      - ipam.ironcore.dev
    resources:
      - prefixallocations
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ipam.ironcore.dev
    resources:
      - prefixallocations/status
    verbs:
      - get
