# permissions for end users to edit prefixes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefix-editor-role
rules:
  - apiGroups:
      - ipam.ironcore.dev
    resources:
      - prefixes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ipam.ironcore.dev
    resources:
      - prefixes/status
    verbs:
      - get
