# permissions for end users to edit storageclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageclass-editor-role
rules:
- apiGroups:
  - storage.onmetal.de
  resources:
  - storageclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - storageclasses/status
  verbs:
  - get
