# permissions for end users to edit volumepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumepool-editor-role
rules:
  - apiGroups:
      - storage.ironcore.dev
    resources:
      - volumepools
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - storage.ironcore.dev
    resources:
      - volumepools/status
    verbs:
      - get
