# permissions for end users to view volumepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumepool-viewer-role
rules:
  - apiGroups:
      - storage.ironcore.dev
    resources:
      - volumepools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.ironcore.dev
    resources:
      - volumepools/status
    verbs:
      - get
