# permissions for end users to view volumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volume-viewer-role
rules:
  - apiGroups:
      - storage.ironcore.dev
    resources:
      - volumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.ironcore.dev
    resources:
      - volumes/status
    verbs:
      - get
