# permissions for end users to view volumeclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumeclaim-viewer-role
rules:
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeclaims/status
  verbs:
  - get
