# permissions for end users to edit volumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volume-editor-role
rules:
  - apiGroups:
      - storage.api.onmetal.de
    resources:
      - volumes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - storage.api.onmetal.de
    resources:
      - volumes/status
    verbs:
      - get
