# permissions for end users to edit volumeclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volumeclaim-editor-role
rules:
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.onmetal.de
  resources:
  - volumeclaims/status
  verbs:
  - get
