apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ironcore-system
  name: ironcore-apiserver
spec:
  template:
    spec:
      containers:
        - name: apiserver
          imagePullPolicy: Never
