apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default
  - broker-rbac

patchesStrategicMerge:
  - patch-manager.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      namespace: volumepoollet-system
      name: volumepoollet-controller-manager
    path: add-args.yaml
