apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: volumepoollet-system
  name: volumepoollet-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
        - name: broker
          imagePullPolicy: Never
