// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// EmptyDiskVolumeSourceApplyConfiguration represents a declarative configuration of the EmptyDiskVolumeSource type for use
// with apply.
type EmptyDiskVolumeSourceApplyConfiguration struct {
	SizeLimit *resource.Quantity `json:"sizeLimit,omitempty"`
}

// EmptyDiskVolumeSourceApplyConfiguration constructs a declarative configuration of the EmptyDiskVolumeSource type for use with
// apply.
func EmptyDiskVolumeSource() *EmptyDiskVolumeSourceApplyConfiguration {
	return &EmptyDiskVolumeSourceApplyConfiguration{}
}

// WithSizeLimit sets the SizeLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SizeLimit field is set to the value of the last call.
func (b *EmptyDiskVolumeSourceApplyConfiguration) WithSizeLimit(value resource.Quantity) *EmptyDiskVolumeSourceApplyConfiguration {
	b.SizeLimit = &value
	return b
}
