// SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// VolumeApplyConfiguration represents a declarative configuration of the Volume type for use
// with apply.
type VolumeApplyConfiguration struct {
	Name                           *string `json:"name,omitempty"`
	Device                         *string `json:"device,omitempty"`
	VolumeSourceApplyConfiguration `json:",inline"`
}

// VolumeApplyConfiguration constructs a declarative configuration of the Volume type for use with
// apply.
func Volume() *VolumeApplyConfiguration {
	return &VolumeApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithName(value string) *VolumeApplyConfiguration {
	b.Name = &value
	return b
}

// WithDevice sets the Device field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Device field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithDevice(value string) *VolumeApplyConfiguration {
	b.Device = &value
	return b
}

// WithVolumeRef sets the VolumeRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeRef field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithVolumeRef(value v1.LocalObjectReference) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.VolumeRef = &value
	return b
}

// WithEmptyDisk sets the EmptyDisk field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmptyDisk field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithEmptyDisk(value *EmptyDiskVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.EmptyDisk = value
	return b
}

// WithLocalDisk sets the LocalDisk field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalDisk field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithLocalDisk(value *LocalDiskVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.LocalDisk = value
	return b
}

// WithEphemeral sets the Ephemeral field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ephemeral field is set to the value of the last call.
func (b *VolumeApplyConfiguration) WithEphemeral(value *EphemeralVolumeSourceApplyConfiguration) *VolumeApplyConfiguration {
	b.VolumeSourceApplyConfiguration.Ephemeral = value
	return b
}
