apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: apiserver
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: system
  labels:
    control-plane: apiserver
spec:
  selector:
    matchLabels:
      control-plane: apiserver
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: apiserver
      labels:
        control-plane: apiserver
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - command:
            - /ironcore-apiserver
          args:
            - --etcd-servers=http://$(IRONCORE_APISERVER_ETCD_SERVICE_NAME):2379
            - --secure-port=8443
            - --audit-log-path=-
            - --enable-priority-and-fairness=false
            - --audit-log-maxage=0
            - --audit-log-maxbackup=0
          image: apiserver:latest
          name: apiserver
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 8443
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /readyz
              port: 8443
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          ports:
            - containerPort: 8443
              name: apiserver
              protocol: TCP
      serviceAccountName: apiserver
      terminationGracePeriodSeconds: 10
