---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: networking.ironcore.dev:system:networkplugins
rules:
  - apiGroups: ["core.apinet.ironcore.dev"]
    resources: ["networkinterfaces"]
    verbs: ["create","get", "update", "patch", "delete", "watch", "list"]
