/*
 * Copyright (c) 2021 by the OnMetal authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/onmetal/onmetal-api/api/networking/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAliasPrefixRoutings implements AliasPrefixRoutingInterface
type FakeAliasPrefixRoutings struct {
	Fake *FakeNetworkingV1alpha1
	ns   string
}

var aliasprefixroutingsResource = schema.GroupVersionResource{Group: "networking.api.onmetal.de", Version: "v1alpha1", Resource: "aliasprefixroutings"}

var aliasprefixroutingsKind = schema.GroupVersionKind{Group: "networking.api.onmetal.de", Version: "v1alpha1", Kind: "AliasPrefixRouting"}

// Get takes name of the aliasPrefixRouting, and returns the corresponding aliasPrefixRouting object, and an error if there is any.
func (c *FakeAliasPrefixRoutings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AliasPrefixRouting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(aliasprefixroutingsResource, c.ns, name), &v1alpha1.AliasPrefixRouting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliasPrefixRouting), err
}

// List takes label and field selectors, and returns the list of AliasPrefixRoutings that match those selectors.
func (c *FakeAliasPrefixRoutings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AliasPrefixRoutingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(aliasprefixroutingsResource, aliasprefixroutingsKind, c.ns, opts), &v1alpha1.AliasPrefixRoutingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AliasPrefixRoutingList{ListMeta: obj.(*v1alpha1.AliasPrefixRoutingList).ListMeta}
	for _, item := range obj.(*v1alpha1.AliasPrefixRoutingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aliasPrefixRoutings.
func (c *FakeAliasPrefixRoutings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(aliasprefixroutingsResource, c.ns, opts))

}

// Create takes the representation of a aliasPrefixRouting and creates it.  Returns the server's representation of the aliasPrefixRouting, and an error, if there is any.
func (c *FakeAliasPrefixRoutings) Create(ctx context.Context, aliasPrefixRouting *v1alpha1.AliasPrefixRouting, opts v1.CreateOptions) (result *v1alpha1.AliasPrefixRouting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(aliasprefixroutingsResource, c.ns, aliasPrefixRouting), &v1alpha1.AliasPrefixRouting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliasPrefixRouting), err
}

// Update takes the representation of a aliasPrefixRouting and updates it. Returns the server's representation of the aliasPrefixRouting, and an error, if there is any.
func (c *FakeAliasPrefixRoutings) Update(ctx context.Context, aliasPrefixRouting *v1alpha1.AliasPrefixRouting, opts v1.UpdateOptions) (result *v1alpha1.AliasPrefixRouting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(aliasprefixroutingsResource, c.ns, aliasPrefixRouting), &v1alpha1.AliasPrefixRouting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliasPrefixRouting), err
}

// Delete takes name of the aliasPrefixRouting and deletes it. Returns an error if one occurs.
func (c *FakeAliasPrefixRoutings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(aliasprefixroutingsResource, c.ns, name, opts), &v1alpha1.AliasPrefixRouting{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAliasPrefixRoutings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(aliasprefixroutingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AliasPrefixRoutingList{})
	return err
}

// Patch applies the patch and returns the patched aliasPrefixRouting.
func (c *FakeAliasPrefixRoutings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AliasPrefixRouting, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(aliasprefixroutingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AliasPrefixRouting{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AliasPrefixRouting), err
}
