apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: apiserver
          volumeMounts:
            - mountPath: /tmp/k8s-apiserver/serving-certs
              name: cert
              readOnly: true
          args:
            - --secure-port=8443
            - --audit-log-path=-
            - --enable-priority-and-fairness=false
            - --audit-log-maxage=0
            - --audit-log-maxbackup=0
            - --tls-cert-file=/tmp/k8s-apiserver/serving-certs/tls.crt
            - --tls-private-key-file=/tmp/k8s-apiserver/serving-certs/tls.key
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: apiserver-cert
