// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/ironcore-dev/ironcore/api/networking/v1alpha1"
	networkingv1alpha1 "github.com/ironcore-dev/ironcore/client-go/applyconfigurations/networking/v1alpha1"
	typednetworkingv1alpha1 "github.com/ironcore-dev/ironcore/client-go/ironcore/versioned/typed/networking/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeVirtualIPs implements VirtualIPInterface
type fakeVirtualIPs struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.VirtualIP, *v1alpha1.VirtualIPList, *networkingv1alpha1.VirtualIPApplyConfiguration]
	Fake *FakeNetworkingV1alpha1
}

func newFakeVirtualIPs(fake *FakeNetworkingV1alpha1, namespace string) typednetworkingv1alpha1.VirtualIPInterface {
	return &fakeVirtualIPs{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.VirtualIP, *v1alpha1.VirtualIPList, *networkingv1alpha1.VirtualIPApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("virtualips"),
			v1alpha1.SchemeGroupVersion.WithKind("VirtualIP"),
			func() *v1alpha1.VirtualIP { return &v1alpha1.VirtualIP{} },
			func() *v1alpha1.VirtualIPList { return &v1alpha1.VirtualIPList{} },
			func(dst, src *v1alpha1.VirtualIPList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VirtualIPList) []*v1alpha1.VirtualIP { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.VirtualIPList, items []*v1alpha1.VirtualIP) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
