apiVersion: compute.ironcore.dev/v1alpha1
kind: Machine
metadata:
  name: machine-sample2
spec:
  machineClassRef:
    name: machineclass-sample
  volumes:
    - name: rootdisk # first disk is root disk
      volumeRef:
        name: volume-sample2
  ignitionRef:
    name: ignition
    key: ignition.yaml
  networkInterfaces:
    - name: primary
      networkInterfaceRef:
        name: networkinterface-sample2
  

