name: Kustomize Validation

on:
  pull_request:
    paths:
    - 'docs/**'
    - '**/*.md'

jobs:
  kustomize-validation:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "No kustomize validation required"'
