name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-**
  pull_request_target:
    types: [ opened, reopened, synchronize ]

permissions:
  contents: read
  pull-requests: read

jobs:
  update_release_draft:
    name: Run release drafter
    if: github.event_name != 'pull_request_target'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      # or a release branch
      - uses: release-drafter/release-drafter@v7
        with:
          commitish: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
  auto_label:
    name: Run autolabeler
    if: github.event_name == 'pull_request_target'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@v7
