name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [ opened, reopened, synchronize ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        with:
          disable-releaser: github.ref != 'refs/heads/main'
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}